-- Seed inicial: dados de exemplo equivalentes aos mocks que hoje vivem em AppContext.tsx
-- Perguntas do diagnóstico entram com score = 0 (ainda não avaliado) — é o estado real
-- de uma fazenda nova, diferente do mock anterior que sorteava notas aleatórias.

-- Propriedades
insert into properties (name, municipio, estado, area_total, area_propria, area_arrendada, latitude, longitude, tipo_solo, altitude, responsavel, culturas, status) values
  ('Fazenda Bela Vista', 'Sorriso', 'MT', 1250, 850, 400, -12.5432, -55.7211, 'Latossolo Vermelho Distrófico (Argiloso)', 365, 'José Augusto Ferreira', array['Soja','Milho','Algodão'], 'Ativa'),
  ('Fazenda Rio Negro', 'Rio Verde', 'GO', 840, 840, 0, -17.7915, -50.9201, 'Latossolo Vermelho-Amarelo (Misto)', 720, 'Mariana de Souza Negrão', array['Soja','Milho','Sorgo'], 'Ativa');

-- Perguntas do diagnóstico (todas iniciam com score 0 = ainda não avaliado)
insert into diagnosis_questions (area, question, score) values
  ('Governança', 'Existe um conselho consultivo ou administrativo estruturado?', 0),
  ('Governança', 'Há acordo formal de sócios e protocolo familiar assinado?', 0),
  ('Governança', 'O processo de sucessão familiar está planejado e documentado?', 0),
  ('Governança', 'As reuniões de resultados ocorrem formalmente com atas registradas?', 0),
  ('Governança', 'Há divisão clara de papéis e responsabilidades entre sócios?', 0),
  ('Governança', 'Existe auditoria externa periódica nos processos e contas?', 0),
  ('Governança', 'A estrutura societária está definida legalmente de forma otimizada?', 0),
  ('Governança', 'Há políticas claras para entrada de novos membros da família no negócio?', 0),
  ('Governança', 'Os pró-labores dos sócios são fixos e separados da distribuição de lucros?', 0),
  ('Governança', 'Existe código de ética e conduta para familiares e gestores?', 0),
  ('Governança', 'A empresa possui holding familiar ou planejamento tributário patrimonial?', 0),
  ('Governança', 'Existe transparência na prestação de contas para acionistas não operacionais?', 0),
  ('Governança', 'As decisões de grandes investimentos passam por alçada formal de aprovação?', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 1)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 2)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 3)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 4)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 5)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 6)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 7)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 8)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 9)', 0),
  ('Governança', 'Pergunta complementar de conformidade e maturidade em Governança (Requisito estratégico Nível 10)', 0),
  ('Financeiro', 'O fluxo de caixa operacional é projetado para 12 meses?', 0),
  ('Financeiro', 'A contabilidade fiscal é integrada com a gestão financeira gerencial?', 0),
  ('Financeiro', 'O DRE gerencial é gerado mensalmente por cultura e atividade?', 0),
  ('Financeiro', 'Há conciliação bancária diária de todas as contas da fazenda?', 0),
  ('Financeiro', 'A margem de contribuição é calculada por talhão e cultura?', 0),
  ('Financeiro', 'Os custos são divididos rigorosamente entre fixos e variáveis?', 0),
  ('Financeiro', 'Há controle exato de contas a pagar e a receber integrado?', 0),
  ('Financeiro', 'Existe definição formal do capital de giro mínimo necessário?', 0),
  ('Financeiro', 'O endividamento total é monitorado com índice de cobertura de juros?', 0),
  ('Financeiro', 'A taxa interna de retorno (TIR) e VPL são calculados para novos investimentos?', 0),
  ('Financeiro', 'Existe orçamento anual estruturado com análise de desvios (realizado vs. orçado)?', 0),
  ('Financeiro', 'O EBITDA é utilizado como principal indicador de eficiência operacional?', 0),
  ('Financeiro', 'Os custos financeiros de empréstimos são monitorados ativamente?', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 1)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 2)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 3)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 4)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 5)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 6)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 7)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 8)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 9)', 0),
  ('Financeiro', 'Pergunta complementar de conformidade e maturidade em Financeiro (Requisito estratégico Nível 10)', 0),
  ('Produção', 'Há planejamento de plantio e colheita georreferenciado por talhão?', 0),
  ('Produção', 'O histórico de produtividade por talhão é registrado e analisado?', 0),
  ('Produção', 'O manejo integrado de pragas e doenças (MIP) é realizado rigorosamente?', 0),
  ('Produção', 'A análise de solo é feita anualmente para recomendação de fertilizantes?', 0),
  ('Produção', 'As perdas na colheita são quantificadas e monitoradas por talhão?', 0),
  ('Produção', 'Existe rotação de culturas planejada de forma sistemática?', 0),
  ('Produção', 'O plantio direto na palha é praticado seguindo recomendações técnicas?', 0),
  ('Produção', 'Os índices pluviométricos e de clima são monitorados e correlacionados com produtividade?', 0),
  ('Produção', 'Há calibração periódica de plantadeiras e pulverizadores?', 0),
  ('Produção', 'Existe planejamento de sementes e insumos baseado no potencial produtivo do talhão?', 0),
  ('Produção', 'A velocidade de plantio é controlada por telemetria?', 0),
  ('Produção', 'Os mapas de produtividade da colheitadeira são processados e arquivados?', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 1)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 2)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 3)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 4)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 5)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 6)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 7)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 8)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 9)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 10)', 0),
  ('Produção', 'Pergunta complementar de conformidade e maturidade em Produção (Requisito estratégico Nível 11)', 0),
  ('Compras', 'Há exigência de cotação mínima de três fornecedores para compras relevantes?', 0),
  ('Compras', 'As compras de insumos chaves (fertilizantes, defensivos) são planejadas com antecedência?', 0),
  ('Compras', 'Há homologação periódica e avaliação técnica de fornecedores?', 0),
  ('Compras', 'O prazo médio de pagamento é negociado alinhado ao fluxo de caixa?', 0),
  ('Compras', 'Há controle de contratos de fornecimento com cláusulas de qualidade e entrega?', 0),
  ('Compras', 'As compras urgentes ou sem planejamento representam menos de 5% do total?', 0),
  ('Compras', 'Há monitoramento do histórico de preços dos principais insumos?', 0),
  ('Compras', 'As compras em grupo ou cooperativas são avaliadas sistematicamente?', 0),
  ('Compras', 'Existe auditoria nas notas fiscais de recebimento em relação ao pedido aprovado?', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 1)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 2)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 3)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 4)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 5)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 6)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 7)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 8)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 9)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 10)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 11)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 12)', 0),
  ('Compras', 'Pergunta complementar de conformidade e maturidade em Compras (Requisito estratégico Nível 13)', 0),
  ('Estoque', 'O controle de entradas e saídas de estoque é totalmente digitalizado?', 0),
  ('Estoque', 'Há rastreabilidade de lotes de defensivos e sementes aplicados?', 0),
  ('Estoque', 'A validade dos produtos químicos é monitorada ativamente com alertas?', 0),
  ('Estoque', 'O estoque mínimo de segurança é definido e integrado ao sistema de compras?', 0),
  ('Estoque', 'O inventário físico de estoque é realizado mensalmente com conciliação?', 0),
  ('Estoque', 'O almoxarifado possui acesso restrito e controle de segurança?', 0),
  ('Estoque', 'Há local adequado e regulamentado para armazenamento de defensivos químicos?', 0),
  ('Estoque', 'As sobras de insumos do campo retornam formalmente para o estoque?', 0),
  ('Estoque', 'O custo médio ponderado do estoque é recalculado a cada nova entrada?', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 1)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 2)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 3)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 4)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 5)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 6)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 7)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 8)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 9)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 10)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 11)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 12)', 0),
  ('Estoque', 'Pergunta complementar de conformidade e maturidade em Estoque (Requisito estratégico Nível 13)', 0),
  ('Máquinas', 'Há plano de manutenção preventiva estruturado para toda a frota?', 0),
  ('Máquinas', 'O consumo de combustível (litros/hora e litros/ha) é monitorado por máquina?', 0),
  ('Máquinas', 'O horímetro das máquinas é registrado diariamente?', 0),
  ('Máquinas', 'O custo de manutenção acumulado por máquina é monitorado para descarte?', 0),
  ('Máquinas', 'A disponibilidade operacional da frota é calculada mensalmente?', 0),
  ('Máquinas', 'Há treinamento de operadores focado em eficiência e condução segura?', 0),
  ('Máquinas', 'As ordens de serviço de manutenção são digitalizadas e integradas aos custos?', 0),
  ('Máquinas', 'Existe controle do índice de patinamento e eficiência de tração dos tratores?', 0),
  ('Máquinas', 'O custo do seguro e proteção patrimonial da frota está atualizado?', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 1)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 2)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 3)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 4)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 5)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 6)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 7)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 8)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 9)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 10)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 11)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 12)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 13)', 0),
  ('Máquinas', 'Pergunta complementar de conformidade e maturidade em Máquinas (Requisito estratégico Nível 14)', 0),
  ('Patrimônio', 'A depreciação gerencial dos ativos (máquinas, benfeitorias) é calculada mensalmente?', 0),
  ('Patrimônio', 'Existe um inventário físico atualizado com plaquetas de identificação dos bens?', 0),
  ('Patrimônio', 'As terras são reavaliadas periodicamente segundo valores de mercado regionais?', 0),
  ('Patrimônio', 'Há seguro patrimonial para instalações, silos e estoques?', 0),
  ('Patrimônio', 'As benfeitorias (galpões, estradas internas) possuem orçamento de conservação?', 0),
  ('Patrimônio', 'O valor atual líquido do patrimônio é reportado no balanço gerencial?', 0),
  ('Patrimônio', 'Os registros imobiliários e CAR (Cadastro Ambiental Rural) estão 100% regularizados?', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 1)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 2)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 3)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 4)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 5)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 6)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 7)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 8)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 9)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 10)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 11)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 12)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 13)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 14)', 0),
  ('Patrimônio', 'Pergunta complementar de conformidade e maturidade em Patrimônio (Requisito estratégico Nível 15)', 0),
  ('Pessoas', 'Existe organograma funcional definido com descrição detalhada de cargos?', 0),
  ('Pessoas', 'Há programa estruturado de treinamento técnico e de segurança (NRs)?', 0),
  ('Pessoas', 'É praticado sistema de metas e bonificação por produtividade ou qualidade?', 0),
  ('Pessoas', 'O índice de turnover (rotatividade) é medido e mantido sob controle?', 0),
  ('Pessoas', 'Há pesquisa periódica de clima organizacional com colaboradores?', 0),
  ('Pessoas', 'O uso de Equipamentos de Proteção Individual (EPI) é obrigatório e fiscalizado?', 0),
  ('Pessoas', 'Há plano de carreira estruturado para reter talentos chaves?', 0),
  ('Pessoas', 'A folha de pagamento e encargos são auditados e pagos sem atrasos?', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 1)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 2)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 3)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 4)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 5)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 6)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 7)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 8)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 9)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 10)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 11)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 12)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 13)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 14)', 0),
  ('Pessoas', 'Pergunta complementar de conformidade e maturidade em Pessoas (Requisito estratégico Nível 15)', 0),
  ('Planejamento', 'Há plano estratégico formalizado para a propriedade com horizontes de 5 anos?', 0),
  ('Planejamento', 'O planejamento financeiro anual inclui análise de cenários otimista, realista e pessimista?', 0),
  ('Planejamento', 'A capacidade de investimento com recursos próprios está claramente mapeada?', 0),
  ('Planejamento', 'Os gargalos logísticos e operacionais são mapeados no início de cada safra?', 0),
  ('Planejamento', 'Os indicadores chaves de performance (KPIs) de cada setor são revisados mensalmente?', 0),
  ('Planejamento', 'Há planos de contingência documentados para crises climáticas ou de mercado?', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 1)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 2)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 3)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 4)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 5)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 6)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 7)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 8)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 9)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 10)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 11)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 12)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 13)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 14)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 15)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 16)', 0),
  ('Planejamento', 'Pergunta complementar de conformidade e maturidade em Planejamento (Requisito estratégico Nível 17)', 0),
  ('Comercialização', 'Existe política de comercialização (trava de preços, hedge, barter) definida?', 0),
  ('Comercialização', 'O custo de carregamento e armazenamento dos grãos é calculado ativamente?', 0),
  ('Comercialização', 'Há diversificação de compradores (tradings, cooperativas, indústrias)?', 0),
  ('Comercialização', 'A qualidade física e química do produto colhido é monitorada e classificada?', 0),
  ('Comercialização', 'Há acompanhamento diário das bolsas (CBOT, B3) e câmbio para tomada de decisão?', 0),
  ('Comercialização', 'O ponto de equilíbrio de preço (break-even) é conhecido antes da venda?', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 1)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 2)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 3)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 4)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 5)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 6)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 7)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 8)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 9)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 10)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 11)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 12)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 13)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 14)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 15)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 16)', 0),
  ('Comercialização', 'Pergunta complementar de conformidade e maturidade em Comercialização (Requisito estratégico Nível 17)', 0),
  ('Tecnologia', 'A conectividade de internet atinge as áreas críticas de operação no campo?', 0),
  ('Tecnologia', 'Utiliza-se telemetria e agricultura de precisão de forma integrada?', 0),
  ('Tecnologia', 'Há backup diário e política de segurança da informação para os dados da fazenda?', 0),
  ('Tecnologia', 'A fazenda utiliza softwares integrados (ERP) reduzindo planilhas manuais?', 0),
  ('Tecnologia', 'São usadas imagens de satélite ou drones para monitorar a sanidade da lavoura?', 0),
  ('Tecnologia', 'Existe automação de processos administrativos e fiscais?', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 1)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 2)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 3)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 4)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 5)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 6)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 7)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 8)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 9)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 10)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 11)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 12)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 13)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 14)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 15)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 16)', 0),
  ('Tecnologia', 'Pergunta complementar de conformidade e maturidade em Tecnologia (Requisito estratégico Nível 17)', 0);

-- Transações financeiras (farm_id resolvido pelo nome da propriedade)
insert into financial_transactions (date, description, type, category, cost_center, farm_id, value, account, status) values
  ('2026-07-01', 'Venda de Soja - Trade Agro', 'receita', 'Venda de Grãos', 'Safra Soja 25/26', (select id from properties where name = 'Fazenda Bela Vista'), 850000, 'Banco do Brasil', 'pago'),
  ('2026-07-02', 'Compra de Adubo NPK - Adubos S/A', 'despesa', 'Insumos / Fertilizantes', 'Safra Soja 25/26', (select id from properties where name = 'Fazenda Bela Vista'), 180000, 'Banco do Brasil', 'pago'),
  ('2026-07-05', 'Diesel COMUM - Posto Rota Oeste', 'despesa', 'Combustíveis', 'Administrativo', (select id from properties where name = 'Fazenda Bela Vista'), 34500, 'Sicredi', 'pago'),
  ('2026-07-10', 'Manutenção Preventiva Trator JD 8R', 'despesa', 'Manutenção de Máquinas', 'Máquinas & Implementos', (select id from properties where name = 'Fazenda Bela Vista'), 15800, 'Sicredi', 'pago'),
  ('2026-07-12', 'Folha de Pagamento - Junho/2026', 'despesa', 'Mão de Obra / Salários', 'Administrativo', (select id from properties where name = 'Fazenda Bela Vista'), 78000, 'Banco do Brasil', 'pago'),
  ('2026-07-14', 'Venda de Milho Safrinha - Granel S/A', 'receita', 'Venda de Grãos', 'Safra Milho 24/25', (select id from properties where name = 'Fazenda Rio Negro'), 430000, 'Itaú', 'pago'),
  ('2026-07-20', 'Seguro Agrícola Safra 25/26 - Porto', 'despesa', 'Seguros', 'Geral', (select id from properties where name = 'Fazenda Bela Vista'), 45000, 'Itaú', 'pendente'),
  ('2026-07-25', 'Parcela Financiamento Colheitadeira', 'despesa', 'Financiamentos / Empréstimos', 'Geral', (select id from properties where name = 'Fazenda Bela Vista'), 120000, 'Banco do Brasil', 'pendente'),
  ('2026-07-08', 'Compra de defensivos - AgroQuímica', 'despesa', 'Insumos / Defensivos', 'Safra Soja 25/26', (select id from properties where name = 'Fazenda Bela Vista'), 92000, 'Sicredi', 'pago'),
  ('2026-07-11', 'Recebimento Frete Lote 3', 'receita', 'Outras Receitas', 'Logística', (select id from properties where name = 'Fazenda Rio Negro'), 18500, 'Sicredi', 'pago');

-- Ativos / patrimônio
insert into assets (name, category, acquisition_date, initial_value, depreciation_rate, useful_life_years, current_value, status) values
  ('Terras Fazenda Bela Vista (Sede)', 'Terras', '2015-05-10', 12000000, 0, 999, 24000000, 'Ativo'),
  ('Trator John Deere 8370R', 'Máquinas', '2021-08-15', 1300000, 10, 10, 650000, 'Ativo'),
  ('Colheitadeira Case IH 9250', 'Máquinas', '2022-04-20', 2400000, 10, 10, 1440000, 'Ativo'),
  ('Semeadora Horsch Maestro 24M', 'Implementos', '2023-09-01', 650000, 12, 8, 429000, 'Ativo'),
  ('Pulverizador Autopropelido Stara Imperador', 'Máquinas', '2020-02-11', 980000, 10, 10, 392000, 'Ativo'),
  ('Silo Secador Metálico 50k sacas', 'Benfeitorias', '2018-06-30', 1800000, 4, 25, 1224000, 'Ativo'),
  ('Rebanho Nelore Cria (250 matrizes)', 'Animais', '2024-03-12', 750000, 0, 99, 810000, 'Ativo');

-- Talhões / produção
insert into crop_fields (name, area, soil_type, culture, crop_year, expected_yield, actual_yield, production_cost_ha, revenue_ha, status) values
  ('Talhão 01 - Entrada', 150, 'Argiloso (45% argila)', 'Soja', '2025/26', 68, 72, 3850, 9720, 'Colhido'),
  ('Talhão 02 - Sede', 220, 'Argiloso (48% argila)', 'Soja', '2025/26', 70, 74, 3900, 9990, 'Colhido'),
  ('Talhão 03 - Rio', 310, 'Misto (30% argila)', 'Milho', '2025/26', 110, 118, 4200, 8850, 'Colhido'),
  ('Talhão 04 - Estrada', 180, 'Arenoso (18% argila)', 'Algodão', '2025/26', 280, 295, 7500, 16500, 'Colhido'),
  ('Talhão 05 - Topo', 390, 'Argiloso (42% argila)', 'Soja', '2025/26', 65, null, 3750, 0, 'Plantado');

-- Máquinas e frota
insert into machines (name, type, hours_worked, fuel_consumed, maintenance_cost, availability, cost_per_hour, status) values
  ('Trator JD 8370R', 'Trator', 1840, 46000, 35800, 94, 115, 'Disponível'),
  ('Colheitadeira Case 9250', 'Colheitadeira', 1120, 39200, 52400, 89, 195, 'Disponível'),
  ('Pulverizador Imperador', 'Pulverizador', 1450, 21750, 28900, 92, 85, 'Em Manutenção'),
  ('Trator MF 4290', 'Trator Pequeno', 2800, 28000, 14500, 98, 45, 'Disponível');

-- Estoque de insumos
insert into stock_items (name, category, quantity, unit, min_quantity, expiry_date, location, value) values
  ('Glifosato Roundup Transorb', 'Defensivos', 2400, 'L', 500, '2027-04-10', 'Depósito Químicos A', 84000),
  ('Fertilizante NPK 04-14-08', 'Nutrição', 45, 'Tons', 10, '2028-10-22', 'Barracão Insumos B', 112500),
  ('Semente Soja M6410 IPRO', 'Sementes', 380, 'Scs', 100, '2026-11-15', 'Câmara Fria C', 95000),
  ('Óleo Diesel S10', 'Combustível', 15000, 'L', 5000, '2027-01-01', 'Tanque Abastecimento', 90000),
  ('Fungicida Fox Xpro', 'Defensivos', 180, 'L', 200, '2026-08-30', 'Depósito Químicos A', 43200);

-- Compras e pedidos
insert into purchase_requests (item, quantity, unit, supplier, value, requester, date, status) values
  ('Fungicida Fox Xpro (400L)', 400, 'L', 'AgroComercial Sorriso', 96000, 'Eng. Agr. Lucas Mantovani', '2026-07-10', 'aprovacao'),
  ('Pneus Trator JD Traseiros (2 un)', 2, 'Un', 'Pneus Oeste Ltda', 24500, 'Mecânico Chefe Sandro', '2026-07-12', 'cotacao'),
  ('Semente Milho DKB 290 PRO3', 150, 'Scs', 'Dekalb Distribuidora', 67500, 'José Augusto Ferreira', '2026-07-05', 'aprovado');

-- Funcionários
insert into employees (name, role, dept, training, performance, status) values
  ('Dr. Lucas Mantovani', 'Engenheiro Agrônomo', 'Produção', '35h', '105%', 'Ativo'),
  ('Sandro Silveira', 'Mecânico Chefe', 'Oficina / Frota', '24h', '98%', 'Ativo'),
  ('Vilmar Souza', 'Operador Especialista John Deere', 'Operações', '40h', '112%', 'Ativo'),
  ('Adriana Nogueira', 'Analista de Custos Pleno', 'Financeiro', '18h', '100%', 'Ativo'),
  ('Sebastião Cruz', 'Gerente Operacional', 'Campo', '30h', '95%', 'Ativo');

